"""Intelligence reporter — generates daily, weekly, and monthly Markdown intelligence reports."""
from __future__ import annotations

import json
from datetime import datetime, timezone
from typing import Any

from langchain_anthropic import ChatAnthropic
from langchain_core.messages import HumanMessage, SystemMessage

from src.config.logging import get_logger
from src.config.settings import get_settings
from src.cognition.cognitive_metrics import CognitiveMetricsCalculator
from src.cognition.performance_tracker import PerformanceTracker

logger = get_logger(__name__)


class IntelligenceReporter:
    """Produces human-readable Markdown intelligence reports.

    Generates daily, weekly, and monthly summaries drawing on cognitive
    metrics and performance data.  LLM is used to produce a narrative
    analysis section for each report.
    """

    def __init__(self) -> None:
        self.settings = get_settings()
        self.llm = ChatAnthropic(
            model=self.settings.anthropic_model,
            api_key=self.settings.ANTHROPIC_API_KEY,
            max_tokens=4096,
        )
        self.metrics_calculator = CognitiveMetricsCalculator()
        self.performance_tracker = PerformanceTracker()

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    async def generate_daily_report(self) -> str:
        """Generate a Markdown-formatted daily intelligence report."""
        logger.info("generating_daily_report")
        return await self._build_report(period="Daily", window_hours=24)

    async def generate_weekly_report(self) -> str:
        """Generate a Markdown-formatted weekly intelligence report."""
        logger.info("generating_weekly_report")
        return await self._build_report(period="Weekly", window_hours=168)

    async def generate_monthly_report(self) -> str:
        """Generate a Markdown-formatted monthly intelligence report."""
        logger.info("generating_monthly_report")
        return await self._build_report(period="Monthly", window_hours=720)

    # ------------------------------------------------------------------
    # Internal
    # ------------------------------------------------------------------

    async def _build_report(self, period: str, window_hours: int) -> str:
        """Assemble the report from metrics, performance data, and LLM narrative."""
        now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

        try:
            cognitive = await self.metrics_calculator.calculate_all()
            token_usage = await self.performance_tracker.get_token_usage(window_hours)
            failure_rate = await self.performance_tracker.get_failure_rate(window_hours)

            # Build the metrics table
            metrics_table = self._render_metrics_table(cognitive)

            # LLM narrative
            narrative = await self._generate_narrative(period, cognitive, token_usage, failure_rate)

            report = (
                f"# {period} Intelligence Report\n\n"
                f"**Generated:** {now}\n\n"
                f"---\n\n"
                f"## Cognitive Metrics\n\n"
                f"{metrics_table}\n\n"
                f"## Performance Summary\n\n"
                f"| Metric | Value |\n"
                f"|--------|-------|\n"
                f"| Total Tokens | {token_usage.get('total_tokens', 0):,} |\n"
                f"| Input Tokens | {token_usage.get('total_input_tokens', 0):,} |\n"
                f"| Output Tokens | {token_usage.get('total_output_tokens', 0):,} |\n"
                f"| Failure Rate | {failure_rate:.2%} |\n\n"
                f"## Analysis\n\n"
                f"{narrative}\n\n"
                f"---\n\n"
                f"*Report auto-generated by IntelligenceReporter*\n"
            )

            logger.info("report_generated", period=period, length=len(report))
            return report
        except Exception as exc:
            logger.error("build_report_failed", period=period, error=str(exc))
            return (
                f"# {period} Intelligence Report\n\n"
                f"**Generated:** {now}\n\n"
                f"Report generation failed: {exc}\n"
            )

    async def _generate_narrative(
        self,
        period: str,
        cognitive: dict[str, Any],
        token_usage: dict[str, Any],
        failure_rate: float,
    ) -> str:
        """Ask the LLM to write a narrative analysis of the data."""
        system_prompt = (
            "You are an intelligence analyst for an autonomous AGI research platform. "
            f"Write a concise {period.lower()} narrative analysis in Markdown "
            "(2-4 paragraphs) covering system health, learning progress, and "
            "actionable recommendations. Do not use code fences."
        )
        human_prompt = (
            f"Cognitive metrics:\n{json.dumps(cognitive, indent=2, default=str)}\n\n"
            f"Token usage:\n{json.dumps(token_usage, indent=2, default=str)}\n\n"
            f"Failure rate: {failure_rate:.2%}"
        )
        try:
            response = await self.llm.ainvoke([
                SystemMessage(content=system_prompt),
                HumanMessage(content=human_prompt),
            ])
            return response.content
        except Exception as exc:
            logger.error("narrative_generation_failed", error=str(exc))
            return "*Narrative could not be generated.*"

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _render_metrics_table(metrics: dict[str, Any]) -> str:
        """Render a dict of metrics as a Markdown table."""
        lines = ["| Metric | Value |", "|--------|-------|"]
        for key, value in metrics.items():
            display_key = key.replace("_", " ").title()
            if isinstance(value, float):
                lines.append(f"| {display_key} | {value:.4f} |")
            else:
                lines.append(f"| {display_key} | {value} |")
        return "\n".join(lines)
