"""
Goal Reflector - Autonomous goal generation from knowledge gaps and patterns.

Analyzes the agent's knowledge, identifies gaps, and generates new objectives
for exploration, learning, and improvement.
"""

import asyncio
import logging
import random
from dataclasses import dataclass, field
from datetime import datetime, timedelta
from typing import Any, Dict, List, Optional, Set
from enum import Enum

from src.cognitive_kernel.kernel import CognitiveKernel
from src.memory.memory_fabric import MemoryFabric, MemoryType
from src.autonomy.objective_manager import Objective, ObjectiveManager, ObjectivePriority

logger = logging.getLogger(__name__)


class GoalSource(Enum):
    """Sources that can generate goals."""
    KNOWLEDGE_GAP = "knowledge_gap"
    PATTERN_DISCOVERY = "pattern_discovery"
    PERFORMANCE_IMPROVEMENT = "performance_improvement"
    CURIOSITY = "curiosity"
    PREDICTIVE = "predictive"
    RECOVERY = "recovery"
    EXPLORATION = "exploration"


@dataclass
class GoalReflectorConfig:
    """Configuration for goal reflection."""
    
    # Timing
    reflection_interval: float = 300.0  # 5 minutes
    min_gap_age_hours: float = 1.0     # Minimum age of gap before acting
    
    # Limits
    max_new_goals_per_reflection: int = 3
    max_active_goals: int = 10
    max_goal_priority: ObjectivePriority = ObjectivePriority.HIGH
    
    # Thresholds
    gap_importance_threshold: float = 0.6
    curiosity_threshold: float = 0.7
    pattern_confidence_threshold: float = 0.7
    
    # Sources to enable
    enabled_sources: List[GoalSource] = field(default_factory=lambda: [
        GoalSource.KNOWLEDGE_GAP,
        GoalSource.PATTERN_DISCOVERY,
        GoalSource.PERFORMANCE_IMPROVEMENT,
        GoalSource.CURIOSITY,
        GoalSource.EXPLORATION,
    ])
    
    # Templates for goal generation
    goal_templates: Dict[GoalSource, List[str]] = field(default_factory=lambda: {
        GoalSource.KNOWLEDGE_GAP: [
            "Investigate and fill knowledge gap about {topic}",
            "Research and understand {topic} thoroughly",
            "Acquire working knowledge of {topic}",
        ],
        GoalSource.PATTERN_DISCOVERY: [
            "Analyze patterns in {domain} for optimization opportunities",
            "Discover recurring patterns in {domain} and document them",
            "Identify common failure modes in {domain}",
        ],
        GoalSource.PERFORMANCE_IMPROVEMENT: [
            "Optimize {component} for better {metric}",
            "Reduce latency in {component} by {target}%",
            "Improve accuracy of {component} on {task}",
        ],
        GoalSource.CURIOSITY: [
            "Explore how {topic} relates to {other_topic}",
            "Investigate the mechanism behind {phenomenon}",
            "Understand why {observation} occurs in {context}",
        ],
        GoalSource.EXPLORATION: [
            "Explore {domain} for novel approaches",
            "Survey state of the art in {domain}",
            "Experiment with {technique} in {context}",
        ],
        GoalSource.PREDICTIVE: [
            "Predict future challenges in {domain} based on trends",
            "Anticipate scaling issues in {component}",
            "Prepare for {scenario} by developing {capability}",
        ],
        GoalSource.RECOVERY: [
            "Develop robustness against {failure_mode}",
            "Create fallback for {critical_component}",
            "Improve error handling for {error_type}",
        ],
    })


@dataclass
class GeneratedGoal:
    """A goal generated by the reflector."""
    description: str
    source: GoalSource
    priority: ObjectivePriority
    curiosity_score: float
    metadata: Dict[str, Any] = field(default_factory=dict)
    template_vars: Dict[str, str] = field(default_factory=dict)


class GoalReflector:
    """
    Reflects on the agent's state, knowledge, and performance to generate
    new autonomous goals.
    
    Sources of goals:
    - Knowledge gaps detected in memory
    - Patterns discovered in experience
    - Performance improvement opportunities
    - Curiosity-driven exploration
    - Predictive anticipation of future needs
    - Recovery from failures
    - Open-ended exploration
    """
    
    def __init__(
        self,
        objective_manager: ObjectiveManager,
        kernel: CognitiveKernel,
        memory_fabric: Optional[MemoryFabric] = None,
        config: Optional[GoalReflectorConfig] = None,
    ):
        self.objective_manager = objective_manager
        self.kernel = kernel
        self.memory_fabric = memory_fabric
        self.config = config or GoalReflectorConfig()
        
        self._last_reflection: Optional[datetime] = None
        self._generated_goals: List[GeneratedGoal] = []
        self._reflection_history: List[Dict[str, Any]] = []
        
        # Statistics
        self._total_reflections = 0
        self._total_goals_generated = 0
        self._goals_by_source: Dict[GoalSource, int] = {s: 0 for s in GoalSource}
    
    async def reflect_and_create(self) -> List[Objective]:
        """
        Perform reflection and create new objectives.
        
        Returns:
            List of newly created objectives
        """
        self._last_reflection = datetime.utcnow()
        self._total_reflections += 1
        
        logger.info("Starting goal reflection")
        
        # Collect potential goals from all enabled sources
        all_goals = []
        
        for source in self.config.enabled_sources:
            try:
                goals = await self._generate_from_source(source)
                all_goals.extend(goals)
            except Exception as e:
                logger.error(f"Goal generation from {source.value} failed: {e}")
        
        # Filter and rank goals
        filtered = self._filter_goals(all_goals)
        
        # Create objectives for top goals
        created = []
        for goal in filtered[:self.config.max_new_goals_per_reflection]:
            try:
                objective = await self._create_objective(goal)
                if objective:
                    created.append(objective)
                    self._total_goals_generated += 1
                    self._goals_by_source[goal.source] += 1
                    logger.info(f"Created goal from {goal.source.value}: {objective.description[:80]}")
            except Exception as e:
                logger.error(f"Failed to create objective: {e}")
        
        # Record reflection
        self._reflection_history.append({
            "timestamp": self._last_reflection.isoformat(),
            "candidates": len(all_goals),
            "filtered": len(filtered),
            "created": len(created),
            "sources": {s.value: sum(1 for g in all_goals if g.source == s) for s in GoalSource},
        })
        
        # Keep history manageable
        if len(self._reflection_history) > 50:
            self._reflection_history = self._reflection_history[-50:]
        
        return created
    
    async def _generate_from_source(self, source: GoalSource) -> List[GeneratedGoal]:
        """Generate goals from a specific source."""
        
        if source == GoalSource.KNOWLEDGE_GAP:
            return await self._find_knowledge_gaps()
        elif source == GoalSource.PATTERN_DISCOVERY:
            return await self._discover_patterns()
        elif source == GoalSource.PERFORMANCE_IMPROVEMENT:
            return await self._find_performance_improvements()
        elif source == GoalSource.CURIOSITY:
            return await self._generate_curiosity_goals()
        elif source == GoalSource.PREDICTIVE:
            return await self._generate_predictive_goals()
        elif source == GoalSource.RECOVERY:
            return await self._generate_recovery_goals()
        elif source == GoalSource.EXPLORATION:
            return await self._generate_exploration_goals()
        
        return []
    
    async def _find_knowledge_gaps(self) -> List[GeneratedGoal]:
        """Identify knowledge gaps from memory queries."""
        goals = []
        
        if not self.memory_fabric:
            return goals
        
        # Query for concepts with low confidence or few connections
        gaps = await self.memory_fabric.query(
            query="unknown uncertain unclear gap missing",
            memory_types=[MemoryType.SEMANTIC, MemoryType.STRUCTURAL],
            limit=10,
        )
        
        for gap in gaps:
            content = gap.get("content", "")
            importance = gap.get("importance", 0.5)
            confidence = gap.get("metadata", {}).get("confidence", 0.5)
            
            # Low confidence or high importance but low detail = gap
            if (confidence < 0.5 and importance > self.config.gap_importance_threshold) or \
               "unknown" in content.lower() or "unclear" in content.lower():
                
                # Extract topic
                topic = self._extract_topic(content)
                
                goals.append(GeneratedGoal(
                    description=self._instantiate_template(
                        GoalSource.KNOWLEDGE_GAP,
                        {"topic": topic}
                    ),
                    source=GoalSource.KNOWLEDGE_GAP,
                    priority=ObjectivePriority.MEDIUM,
                    curiosity_score=1.0 - confidence,
                    metadata={
                        "gap_content": content[:200],
                        "original_confidence": confidence,
                        "importance": importance,
                    },
                    template_vars={"topic": topic},
                ))
        
        return goals
    
    async def _discover_patterns(self) -> List[GeneratedGoal]:
        """Discover patterns in experience for optimization."""
        goals = []
        
        if not self.memory_fabric:
            return goals
        
        # Look for recurring situations
        experiences = await self.memory_fabric.query(
            query="pattern recurring repeated similar",
            memory_types=[MemoryType.EPISODIC, MemoryType.PROCEDURAL],
            limit=20,
        )
        
        # Group by domain/context
        domains = {}
        for exp in experiences:
            meta = exp.get("metadata", {})
            domain = meta.get("domain", meta.get("context", "general"))
            if domain not in domains:
                domains[domain] = []
            domains[domain].append(exp)
        
        # Generate goals for domains with multiple experiences
        for domain, exps in domains.items():
            if len(exps) >= 3:
                # Use kernel to analyze pattern
                try:
                    result = await self.kernel.process({
                        "type": "pattern_analysis",
                        "domain": domain,
                        "experiences": [e.get("content", "")[:200] for e in exps[:5]],
                        "task": "Identify optimization opportunities and recurring patterns",
                    })
                    
                    decision = result.get("decision", {})
                    if decision.get("confidence", 0) > self.config.pattern_confidence_threshold:
                        goals.append(GeneratedGoal(
                            description=self._instantiate_template(
                                GoalSource.PATTERN_DISCOVERY,
                                {"domain": domain}
                            ),
                            source=GoalSource.PATTERN_DISCOVERY,
                            priority=ObjectivePriority.MEDIUM,
                            curiosity_score=decision.get("confidence", 0.5),
                            metadata={
                                "domain": domain,
                                "experience_count": len(exps),
                                "analysis": decision.get("reasoning", ""),
                            },
                            template_vars={"domain": domain},
                        ))
                except Exception as e:
                    logger.debug(f"Pattern analysis failed for {domain}: {e}")
        
        return goals
    
    async def _find_performance_improvements(self) -> List[GeneratedGoal]:
        """Identify performance improvement opportunities."""
        goals = []
        
        # This would integrate with metrics/monitoring
        # For now, generate from known components
        components = ["cognitive_kernel", "memory_fabric", "reasoning_hub", "attention_manager"]
        metrics = ["latency", "accuracy", "throughput", "memory_usage"]
        
        for comp in components:
            for metric in metrics:
                if random.random() < 0.3:  # 30% chance per combination
                    target = random.randint(10, 50)
                    goals.append(GeneratedGoal(
                        description=self._instantiate_template(
                            GoalSource.PERFORMANCE_IMPROVEMENT,
                            {"component": comp, "metric": metric, "target": str(target)}
                        ),
                        source=GoalSource.PERFORMANCE_IMPROVEMENT,
                        priority=ObjectivePriority.LOW,
                        curiosity_score=0.5,
                        metadata={
                            "component": comp,
                            "metric": metric,
                            "target_improvement": target,
                        },
                        template_vars={
                            "component": comp,
                            "metric": metric,
                            "target": str(target),
                        },
                    ))
        
        return goals[:3]  # Limit
    
    async def _generate_curiosity_goals(self) -> List[GeneratedGoal]:
        """Generate goals from curiosity about connections."""
        goals = []
        
        if not self.memory_fabric:
            return goals
        
        # Get diverse concepts
        concepts = await self.memory_fabric.query(
            query="concept mechanism phenomenon principle",
            memory_types=[MemoryType.SEMANTIC],
            limit=10,
        )
        
        concept_list = [c.get("content", "") for c in concepts if c.get("content")]
        
        # Pair random concepts
        for _ in range(3):
            if len(concept_list) >= 2:
                c1, c2 = random.sample(concept_list, 2)
                topic1 = self._extract_topic(c1)
                topic2 = self._extract_topic(c2)
                
                if topic1 != topic2:
                    goals.append(GeneratedGoal(
                        description=self._instantiate_template(
                            GoalSource.CURIOSITY,
                            {"topic": topic1, "other_topic": topic2}
                        ),
                        source=GoalSource.CURIOSITY,
                        priority=ObjectivePriority.LOW,
                        curiosity_score=0.8,
                        metadata={
                            "concept_a": c1[:100],
                            "concept_b": c2[:100],
                        },
                        template_vars={"topic": topic1, "other_topic": topic2},
                    ))
        
        return goals
    
    async def _generate_predictive_goals(self) -> List[GeneratedGoal]:
        """Generate goals anticipating future needs."""
        goals = []
        
        domains = ["agent_scaling", "memory_growth", "reasoning_complexity", "multi_agent_coordination"]
        
        for domain in random.sample(domains, min(2, len(domains))):
            goals.append(GeneratedGoal(
                description=self._instantiate_template(
                    GoalSource.PREDICTIVE,
                    {"domain": domain, "scenario": f"increased {domain}", "capability": f"scalable {domain}"}
                ),
                source=GoalSource.PREDICTIVE,
                priority=ObjectivePriority.LOW,
                curiosity_score=0.6,
                metadata={"domain": domain},
                template_vars={"domain": domain, "scenario": f"increased {domain}", "capability": f"scalable {domain}"},
            ))
        
        return goals
    
    async def _generate_recovery_goals(self) -> List[GeneratedGoal]:
        """Generate goals for recovery and robustness."""
        goals = []
        
        if not self.memory_fabric:
            return goals
        
        # Look for past failures
        failures = await self.memory_fabric.query(
            query="error failure exception crash",
            memory_types=[MemoryType.EPISODIC],
            limit=10,
        )
        
        for fail in failures[:3]:
            error_type = fail.get("metadata", {}).get("error_type", "unknown")
            component = fail.get("metadata", {}).get("component", "system")
            
            goals.append(GeneratedGoal(
                description=self._instantiate_template(
                    GoalSource.RECOVERY,
                    {"failure_mode": error_type, "critical_component": component, "error_type": error_type}
                ),
                source=GoalSource.RECOVERY,
                priority=ObjectivePriority.HIGH,
                curiosity_score=0.4,
                metadata={
                    "original_failure": fail.get("content", "")[:200],
                    "error_type": error_type,
                    "component": component,
                },
                template_vars={
                    "failure_mode": error_type,
                    "critical_component": component,
                    "error_type": error_type,
                },
            ))
        
        return goals
    
    async def _generate_exploration_goals(self) -> List[GeneratedGoal]:
        """Generate open-ended exploration goals."""
        goals = []
        
        domains = [
            "neural-symbolic integration",
            "continual learning",
            "causal reasoning",
            "meta-learning",
            "agent communication protocols",
            "memory consolidation strategies",
        ]
        
        for domain in random.sample(domains, min(2, len(domains))):
            goals.append(GeneratedGoal(
                description=self._instantiate_template(
                    GoalSource.EXPLORATION,
                    {"domain": domain, "technique": domain, "context": "autonomous agents"}
                ),
                source=GoalSource.EXPLORATION,
                priority=ObjectivePriority.LOW,
                curiosity_score=0.9,
                metadata={"domain": domain},
                template_vars={"domain": domain, "technique": domain, "context": "autonomous agents"},
            ))
        
        return goals
    
    def _filter_goals(self, goals: List[GeneratedGoal]) -> List[GeneratedGoal]:
        """Filter and rank goals by quality."""
        
        # Remove duplicates by description similarity
        unique = []
        seen_descriptions = set()
        
        for goal in goals:
            key = goal.description.lower()[:50]
            if key not in seen_descriptions:
                seen_descriptions.add(key)
                unique.append(goal)
        
        # Check against existing active objectives
        active = self.objective_manager.get_active_objectives()
        active_descriptions = {obj.description.lower()[:50] for obj in active}
        
        filtered = [g for g in unique if g.description.lower()[:50] not in active_descriptions]
        
        # Check max active goals limit
        if len(active) + len(filtered) > self.config.max_active_goals:
            filtered = filtered[:self.config.max_active_goals - len(active)]
        
        # Rank by curiosity score * priority weight
        priority_weights = {
            ObjectivePriority.CRITICAL: 1.0,
            ObjectivePriority.HIGH: 0.8,
            ObjectivePriority.MEDIUM: 0.6,
            ObjectivePriority.LOW: 0.4,
            ObjectivePriority.BACKGROUND: 0.2,
        }
        
        filtered.sort(
            key=lambda g: g.curiosity_score * priority_weights.get(g.priority, 0.5),
            reverse=True
        )
        
        return filtered
    
    async def _create_objective(self, goal: GeneratedGoal) -> Optional[Objective]:
        """Create an Objective from a GeneratedGoal."""
        
        # Check priority limit
        priority_order = [ObjectivePriority.CRITICAL, ObjectivePriority.HIGH, 
                         ObjectivePriority.MEDIUM, ObjectivePriority.LOW, ObjectivePriority.BACKGROUND]
        
        if priority_order.index(goal.priority) < priority_order.index(self.config.max_goal_priority):
            goal.priority = self.config.max_goal_priority
        
        return self.objective_manager.set_objective(
            description=goal.description,
            priority=goal.priority,
            metadata={
                **goal.metadata,
                "source": goal.source.value,
                "curiosity_score": goal.curiosity_score,
                "template_vars": goal.template_vars,
                "generated_at": datetime.utcnow().isoformat(),
            }
        )
    
    def _extract_topic(self, content: str) -> str:
        """Extract a concise topic from content."""
        # Simple extraction - take first meaningful phrase
        words = content.split()
        if len(words) <= 5:
            return content
        return " ".join(words[:5]) + "..."
    
    def _instantiate_template(self, source: GoalSource, vars: Dict[str, str]) -> str:
        """Instantiate a goal template with variables."""
        templates = self.config.goal_templates.get(source, ["Investigate {topic}"])
        template = random.choice(templates)
        
        for key, value in vars.items():
            template = template.replace(f"{{{key}}}", value)
        
        return template
    
    def get_stats(self) -> Dict[str, Any]:
        """Get reflector statistics."""
        return {
            "total_reflections": self._total_reflections,
            "total_goals_generated": self._total_goals_generated,
            "goals_by_source": {s.value: c for s, c in self._goals_by_source.items()},
            "last_reflection": self._last_reflection.isoformat() if self._last_reflection else None,
            "recent_reflections": len(self._reflection_history),
        }
    
    def get_history(self, limit: int = 10) -> List[Dict[str, Any]]:
        """Get reflection history."""
        return self._reflection_history[-limit:]